### ISSUE TITLE
Formatting Help/Question

### ISSUE THREAD

**Issue by jwilczek** [dajomas/slackalert#3]
This is not necessarily an issue (but it may be).

Could you possibly provide some example searches demonstrating the formatting for messages? Sending single results explicitly referencing each field ($result.field1$, $result.field2$, etc) works as expected. However, after days of testing and playing around with formatting, I'm unable to send multiple results using {}. 

Could you please provide a few examples of this?

Thank you!

**Comment by dajomas** [comment]
Hi there,

thank you for using slackalert!

if you have a search that returns multiple events, you should reference
them as follows:

{field1} {field2}

I will send you some screenshots of how I use it myself soon.

Greetinx
Johan

**Comment by dajomas** [comment]
As promised,

here is a bit more detail on how I use the macro expansion in slackalert:

This is my search. It checks my Philips Hue bridge to see if any of the
Philips Hue light bulbs are unreachable:
index=hue_test
| spath path={}.name output=Name
| spath path={}.state.reachable output=Reachable
| where Reachable == "false"
| eval severity = "CRIT"
| eval channel = "testing_ground"
| eval message = "Lightbulb " + Name + " is unreachable"
| table Name, severity, message, _time
| sort +Name, +_time

In the alert configuration, the Mandatory Fields section looks as follows:
[image: Inline image 2]
In stead of pointing to the Message Field "message" I could have set the
value in Message as follows: Lightbulb {Name} is unreachable

Next, I have included the field Name as follows:
[image: Inline image 1]
And the fields in the Message Format section are:
[image: Inline image 3]

This result in of the search:
[image: Inline image 4]

Will result in these Slack messages:
[image: Inline image 5]

I hope this helps you further, if you still have some questions, please let
me know!

Greetinx
Johan

**Comment by dajomas** [comment]
As promised,

here is a bit more detail on how I use the macro expansion in slackalert:

This is my search. It checks my Philips Hue bridge to see if any of the
Philips Hue light bulbs are unreachable:
index=hue_test
| spath path={}.name output=Name
| spath path={}.state.reachable output=Reachable
| where Reachable == "false"
| eval severity = "CRIT"
| eval channel = "testing_ground"
| eval message = "Lightbulb " + Name + " is unreachable"
| table Name, severity, message, _time
| sort +Name, +_time


**In the alert configuration, the Mandatory Fields section looks as follows:**
![image](https://cloud.githubusercontent.com/assets/5916945/25515671/71b97aa0-2be6-11e7-80e2-a25a3dc7b3da.png)

In stead of pointing to the Message Field "message" I could have set the
value in Message as follows: Lightbulb {Name} is unreachable


**Next, I have included the field Name as follows:**
![image](https://cloud.githubusercontent.com/assets/5916945/25515649/4b324f9c-2be6-11e7-8a60-0d0b4d341f0f.png)


**And the fields in the Message Format section are:**
![image](https://cloud.githubusercontent.com/assets/5916945/25515677/7e3bccce-2be6-11e7-9028-b065b194d5f2.png)


**This result in of the search:**
![image](https://cloud.githubusercontent.com/assets/5916945/25515679/845164d4-2be6-11e7-9034-82579ac21f3e.png)


**Will result in these Slack messages:**
![image](https://cloud.githubusercontent.com/assets/5916945/25515682/8944334a-2be6-11e7-9370-ffdc5553aa0c.png)


I hope this helps you further, if you still have some questions, please let
me know!

**Comment by jwilczek** [comment]
Hmm, I think I see the issue....

First, thanks for the examples! These will help for certain!

Second, the version of the app we installed in Splunk is not this one... We pulled a version from splunk.com (which I think is probably an older version)? We'll look into updating our version of the app and I'll let you know.

Thank  you!

**Comment by jwilczek** [comment]
Ok, we now have the correct version. I believe I have it configured properly, but I'm not ever seeing any results sent to the slack channel.

**Comment by jwilczek** [comment]
Is it possible to just send a table of results?

**Comment by dajomas** [comment]
Not yet, that is something I will be working on soon.

**Comment by dajomas** [comment]
@jwilczek Unfortunately, Slack does not support tables. So it will not be possible to send a table of results as a table. One option could be to send the table as comma separated (CSV-like) output but I don't think Slack would be the right target platform for that.
